function execute_load_trace(trace_file)


% Authors: Pooyan Jamshidi (pooyan.jamshidi@gmail.com)
% The code is released under the FreeBSD License.
% Copyright (C) 2016 Pooyan Jamshidi, Imperial College London

trace=csvread(trace_file);

% we first measure how many messages per second can be generated by each worker
number_of_message_per_sec=execute_workload('text',1000,30)/30; 

for i=1:length(trace)
    time_to_next_load_level=trace(i,1);
    load_level=trace(i,2);
    parallelism=round(load_level/number_of_message_per_sec);
    total_number_of_message_pushed=execute_workload('text',time_to_next_load_level*60*1000,parallelism) % convert time to milliseconds
end


end