function execute_load_trace(trace_file)
% replays a workload trace trace_file
% trace_file is the name of the file containing the trace

% Authors: Pooyan Jamshidi (pooyan.jamshidi@gmail.com)
% The code is released under the FreeBSD License.
% Copyright (C) 2016 Pooyan Jamshidi, Imperial College London

p=gcp(); % get the current parallel pool

trace=csvread(trace_file);
% we first measure how many messages per second can be generated by each worker
number_of_message_per_sec=execute_workload('text',1000,30)/30;
%time_period=trace(end,1)-trace(1,1);
%parfeval(p,@get_arrival_rate,1,time_period);

relative_time=0;
for i=1:length(trace)
    time_to_next_load_level=trace(i,1)-relative_time;
    relative_time=trace(i,1);
    load_level=trace(i,2);
    fprintf('pay load is switched to %d (tuples/sec)\n', load_level);
    parallelism=round(load_level/number_of_message_per_sec);
    execute_workload('text',time_to_next_load_level*60*1000,parallelism); % convert time to milliseconds
end


end