component.count_bolt_num: 1
component.split_bolt_num: 1
component.spout_num: 3
dev.zookeeper.path: /tmp/dev-storm-zookeeper
drpc.authorizer.acl.filename: drpc-auth-acl.yaml
drpc.authorizer.acl.strict: false
drpc.childopts: -Xmx768m
drpc.http.creds.plugin: backtype.storm.security.auth.DefaultHttpCredentialsPlugin
drpc.http.port: 3774
drpc.https.keystore.password: 
drpc.https.keystore.type: JKS
drpc.https.port: -1
drpc.invocations.port: 3773
drpc.invocations.threads: 64
drpc.max_buffer_size: 1048576
drpc.port: 3772
drpc.queue.size: 128
drpc.request.timeout.secs: 600
drpc.worker.threads: 64
java.library.path: /usr/local/lib:/opt/local/lib:/usr/lib
logs.users: null
logviewer.appender.name: A1
logviewer.childopts: -Xmx128m
logviewer.cleanup.age.mins: 10080
logviewer.port: 8000
metrics.enabled: true
metrics.path: reports
metrics.poll: 1000
metrics.time: 300000
nimbus.childopts: -Xmx1024m
nimbus.cleanup.inbox.freq.secs: 600
nimbus.credential.renewers.freq.secs: 600
nimbus.file.copy.expiration.secs: 600
nimbus.host: nimbus
nimbus.inbox.jar.expiration.secs: 3600
nimbus.monitor.freq.secs: 10
nimbus.reassign: true
nimbus.supervisor.timeout.secs: 60
nimbus.task.launch.secs: 120
nimbus.task.timeout.secs: 30
nimbus.thrift.max_buffer_size: 1048576
nimbus.thrift.port: 6627
nimbus.thrift.threads: 64
nimbus.topology.validator: backtype.storm.nimbus.DefaultTopologyValidator
storm.auth.simple-acl.admins: []
storm.auth.simple-acl.users: []
storm.auth.simple-acl.users.commands: []
storm.auth.simple-white-list.users: []
storm.cluster.mode: distributed
storm.group.mapping.service: backtype.storm.security.auth.ShellBasedGroupsMapping
storm.group.mapping.service.cache.duration.secs: 120
storm.local.dir: storm-local
storm.local.mode.zmq: false
storm.messaging.netty.authentication: false
storm.messaging.netty.buffer_size: 5242880
storm.messaging.netty.client_worker_threads: 1
storm.messaging.netty.flush.check.interval.ms: 10
storm.messaging.netty.max_retries: 300
storm.messaging.netty.max_wait_ms: 1000
storm.messaging.netty.min_wait_ms: 100
storm.messaging.netty.server_worker_threads: 1
storm.messaging.netty.socket.backlog: 500
storm.messaging.netty.transfer.batch.size: 262144
storm.messaging.transport: backtype.storm.messaging.netty.Context
storm.meta.serialization.delegate: backtype.storm.serialization.GzipThriftSerializationDelegate
storm.nimbus.retry.interval.millis: 2000
storm.nimbus.retry.intervalceiling.millis: 60000
storm.nimbus.retry.times: 5
storm.principal.tolocal: backtype.storm.security.auth.DefaultPrincipalToLocal
storm.thrift.transport: backtype.storm.security.auth.SimpleTransportPlugin
storm.zookeeper.auth.password: null
storm.zookeeper.auth.user: null
storm.zookeeper.connection.timeout: 15000
storm.zookeeper.port: 2181
storm.zookeeper.retry.interval: 1000
storm.zookeeper.retry.intervalceiling.millis: 30000
storm.zookeeper.retry.times: 5
storm.zookeeper.root: /storm
storm.zookeeper.servers: [localhost]
storm.zookeeper.session.timeout: 20000
supervisor.childopts: -Xmx256m
supervisor.enable: true
supervisor.heartbeat.frequency.secs: 5
supervisor.monitor.frequency.secs: 3
supervisor.run.worker.as.user: false
supervisor.slots.ports: [6700, 6701, 6702, 6703]
supervisor.supervisors: []
supervisor.supervisors.commands: []
supervisor.worker.shutdown.sleep.secs: 1
supervisor.worker.start.timeout.secs: 120
supervisor.worker.timeout.secs: 30
task.credentials.poll.secs: 30
task.heartbeat.frequency.secs: 3
task.refresh.poll.secs: 1
topology.acker.executors: 3
topology.bolts.outgoing.overflow.buffer.enable: false
topology.builtin.metrics.bucket.size.secs: 1
topology.classpath: null
topology.debug: false
topology.disruptor.wait.strategy: com.lmax.disruptor.BlockingWaitStrategy
topology.enable.message.timeouts: true
topology.environment: null
topology.error.throttle.interval.secs: 10
topology.executor.receive.buffer.size: 1024
topology.executor.send.buffer.size: 1024
topology.fall.back.on.java.serialization: true
topology.kryo.factory: backtype.storm.serialization.DefaultKryoFactory
topology.max.error.report.per.interval: 5
topology.max.spout.pending: 100
topology.max.task.parallelism: null
topology.message.timeout.secs: 30
topology.multilang.serializer: backtype.storm.multilang.JsonSerializer
topology.name: WordCount
topology.skip.missing.kryo.registrations: false
topology.sleep.spout.wait.strategy.time.ms: 1
topology.spout.wait.strategy: backtype.storm.spout.SleepSpoutWaitStrategy
topology.state.synchronization.timeout.secs: 60
topology.stats.sample.rate: 0.05
topology.tasks: null
topology.testing.always.try.serialize: false
topology.tick.tuple.freq.secs: null
topology.transfer.buffer.size: 1024
topology.trident.batch.emit.interval.millis: 500
topology.tuple.serializer: backtype.storm.serialization.types.ListDelegateSerializer
topology.worker.childopts: null
topology.worker.receiver.thread.count: 1
topology.worker.shared.thread.pool.size: 4
topology.workers: 3
transactional.zookeeper.port: null
transactional.zookeeper.root: /transactional
transactional.zookeeper.servers: null
ui.actions.enabled: true
ui.childopts: -Xmx768m
ui.filter: null
ui.filter.params: null
ui.header.buffer.bytes: 4096
ui.host: 0.0.0.0
ui.http.creds.plugin: backtype.storm.security.auth.DefaultHttpCredentialsPlugin
ui.port: 8080
ui.users: null
worker.childopts: -Xmx768m
worker.gc.childopts: 
worker.heartbeat.frequency.secs: 1
zmq.hwm: 0
zmq.linger.millis: 5000
zmq.threads: 1
