# information about the experiment
runexp:
  noise: 1e-5
  numIter: 100
  initialDesign: 10
  saveFolder: "./integrated/reports/"
  confFolder: "./integrated/config/"
  summaryFolder: "./integrated/summary/"
  blueprint: "storm-fco.yaml"
  conf: "wordcount.yaml"
  topic: "jsontest" # kafka configurations, this topic is used for pushing testing tuples into
  sleep_time: 10000
  metricPoll: 1000
  expTime: 300000
# the url of the services confioguration optimization is depend on or use
services:
  - servicename: "deployment.service"
    URL: "URL"
    container: "CONTAINER ID"
    username: "USERNAME"
    password: "PASSWORD"
    tools: "/Repos/DICE-Deployment-Service/tools"
  - servicename: "continuousintegration.service"
    URL: "localhost:4985"
  - servicename: "monitoring.service"
    URL: "URL"
  - servicename: "storm_ui"
    URL: "URL"
    ip: "IP"
    username: "USERNAME"
    password: "PASSWORD"  
    storm_client: "/usr/share/storm/0.9.3/"  
  - servicename: "broker"
    URL: "URL" # kafka  
  - servicename: "zookeeper.servers"
    URL: "URL" # kafka 
    ip: ["IP"]
application:
  jar_file: "storm-starter-0.9.3.jar"
  jar_path: URL # this is a URL from which the jar file will be submited, you can put the prepared jar file into dropbox and use the dropbox link here
  class: "storm.starter.WordCountTopology"
  name: "wordcount"
  type: "storm"
# information about the parameters, note that for each parameter the specific technology
# , e.g., storm, is also specified via "node"
vars:
  - paramname: "component.spout_num" 
    node: ["storm", "nimbus"] 
    options: [1 3]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "topology.max.spout.pending" 
    node: ["storm", "nimbus"] 
    options: [1 2 10 100 1000 10000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "topology.sleep.spout.wait.strategy.time.ms"
    node: ["storm", "nimbus"]  
    options: [1 2 3 10 100]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.split_bolt_num"
    node: ["storm", "nimbus"]  
    options: [1 2 3 6]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.count_bolt_num" 
    node: ["storm", "nimbus"]  
    options: [1 3 6 12]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "storm.messaging.netty.min_wait_ms"  
    node: ["storm", "nimbus"] 
    options: [10 100 1000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  # - paramname: "tickTime"
  #   node: "zookeeper"
  #   options: [2000 3000 4000]
  #   lowerbound: 0
  #   upperbound: 0
  #   integer: 0
  #   categorical: 1
  # - paramname: "initLimit"
  #   node: "zookeeper"
  #   options: [5 10 15]
  #   lowerbound: 0
  #   upperbound: 0
  #   integer: 0
  #   categorical: 1
  # - paramname: "syncLimit"
  #   node: zookeeper
  #   options: [2 3 4]
  #   lowerbound: 0
  #   upperbound: 0
  #   integer: 0
  #   categorical: 1