# information about the experiment
runexp:
  noise: 1e-5
  numIter: 100
  initialDesign: 10
  saveFolder: ./reports/
  confFolder: ./config/
  topologyName: "WordCount"
  conf: "wordcount.yaml"
  sleep_time: 10000
  metricPoll: 1000
  expTime: 60000
# the url of the services confioguration optimization is depend on or use
services:
  deploymentServiceURL: "localhost:4984"
  continuousIntegrationURL: "localhost:4985"
  monitoringURL: "http://109.231.121.139:5001"
  stormUIURL: "http://109.231.121.245:8080"
# information about the parameters
vars:
  - paramname: "component.spout_num"  
    options: [1 3]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "topology.max.spout.pending" 
    options: [1 2 10 100 1000 10000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "topology.sleep.spout.wait.strategy.time.ms" 
    options: [1 2 3 10 100]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.split_bolt_num" 
    options: [1 2 3 6]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.count_bolt_num" 
    options: [1 3 6 12]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "storm.messaging.netty.min_wait_ms"  
    options: [10 100 1000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1