tosca_definitions_version: cloudify_dsl_1_2

imports:
  - http://www.getcloudify.org/spec/cloudify/3.3.1/types.yaml
  - https://raw.githubusercontent.com/dice-project/DICE-FCO-Plugin-Cloudify/master/plugin.yaml
  - https://raw.githubusercontent.com/dice-project/cloudify-chef-plugin/redirect/plugin.yaml
  - http://dice-project.github.io/DICE-Deployment-Cloudify/spec/fco/0.1.1/plugin.yaml

inputs:
  agent_user:
    default: ubuntu

  # There is some renaming of the inputs in the pipeline in order to make it
  # more consistent (all ids instead of names)
  small_image_id:
    default: 87978c6d-5ceb-39b2-8e8b-935503ad0307
  small_server_type:
    default: 2 GB / 1 CPU
  small_disk:
    default: 30Gb Storage

  medium_image_id:
    default: 87978c6d-5ceb-39b2-8e8b-935503ad0307
  medium_server_type:
    default: 2 GB / 1 CPU
  medium_disk:
    default: 30Gb Storage

  large_image_id:
    default: 87978c6d-5ceb-39b2-8e8b-935503ad0307
  large_server_type:
    default: 2 GB / 1 CPU
  large_disk:
    default: 30Gb Storage

  # The need for various user credentials will be removed as soon as possible,
  # but current version of Flexiant plugin is not mature enough to be able to
  # set credentials at bootstrap time.
  username:
    default: <username>
  password:
    default: <password>
  customer:
    default: <customer>
  service_url:
    default: <FCO base url>
  agent_key:
    default: <agent key uuid>
  vdc:
    default: <VDC uuid>
  network:
    default: <network uuid>


node_templates:
  zookeeper_vm:
    type: dice.hosts.Medium
    instances:
      deploy: 1

  zookeeper_quorum:
    type: dice.components.zookeeper.Quorum
    relationships:
      - type: dice.relationships.zookeeper.QuorumContains
        target: zookeeper_vm

  zookeeper:
    type: dice.components.zookeeper.Server
    properties:
      configuration:
        tickTime: 2000
        initLimit: 5
        syncLimit: 2
    relationships:
      - type: dice.relationships.ContainedIn
        target: zookeeper_vm
      - type: dice.relationships.zookeeper.MemberOfQuorum
        target: zookeeper_quorum

  nimbus_vm:
    type: dice.hosts.Medium

  nimbus:
    type: dice.components.storm.Nimbus
    relationships:
      - type: dice.relationships.ContainedIn
        target: nimbus_vm
      - type: dice.relationships.storm.ConnectedToZookeeperQuorum
        target: zookeeper_quorum

  storm_vm:
    type: dice.hosts.Medium
    instances:
      deploy: 2

  storm:
    type: dice.components.storm.Worker
    relationships:
      - type: dice.relationships.ContainedIn
        target: storm_vm
      - type: dice.relationships.storm.ConnectedToZookeeperQuorum
        target: zookeeper_quorum
      - type: dice.relationships.storm.ConnectedToNimbus
        target: nimbus

  wordcount:
    type: dice.components.storm.Topology
    properties:
      application: http://109.231.122.66/jenkins/view/DICE%20Review/job/02%20Build%20Word%20Count/lastSuccessfulBuild/artifact/target/storm-starter-0.9.3.jar
      topology_name: dice-wordcount
      topology_class: storm.starter.WordCountTopology
    relationships:
      - type: dice.relationships.storm.SubmittedBy
        target: nimbus
      - type: dice.relationships.Needs
        target: storm


outputs:
  storm_nimbus_address:
    description: The address to be used by the storm client
    value: { get_attribute: [nimbus_vm, ip] }
  storm_nimbus_gui:
    description: URL of the Storm nimbus gui
    value:
      concat: [ 'http://', { get_attribute: [nimbus_vm, ip] }, ':8080' ]
  wordcount_id:
    description: Unique Storm topology ID
    value: { get_attribute: [ wordcount, topology_id ] }
